/* THIS FILE IS GENERATED BY SETUP: DO NOT EDIT */
#ifndef IMOD_CONFIG_INCLUDED
#define IMOD_CONFIG_INCLUDED
#define VERSION              417
#define VERSION_NAME "4.1.7"
#define COPYRIGHT_YEARS "1994-2010"
#define LAB_NAME1 "Boulder Laboratory for 3-Dimensional"
#define LAB_NAME2 "Electron Microscopy of Cells"
#define B3D_LITTLE_ENDIAN
#define SWAP_IEEE_FLOATS
#define SENDEVENT_RETRY_HACK 0
#define CTRL_STRING "Ctrl"
typedef char b3dByte;
typedef unsigned char b3dUByte;
typedef short int b3dInt16;
typedef unsigned short int b3dUInt16;
typedef int b3dInt32;
typedef unsigned int b3dUInt32;
typedef float b3dFloat;

#endif
 
