/* soapH.h
   Generated by gSOAP 2.7.17 from txbrHeader.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_SCOPE
#define SOAP_TYPE_SCOPE (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SCOPE(struct soap*, enum SCOPE *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SCOPE(struct soap*, const char*, int, const enum SCOPE *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_SCOPE2s(struct soap*, enum SCOPE);
SOAP_FMAC3 enum SCOPE * SOAP_FMAC4 soap_in_SCOPE(struct soap*, const char*, enum SCOPE *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2SCOPE(struct soap*, const char*, enum SCOPE *);

#define soap_write_SCOPE(soap, data) ( soap_begin_send(soap) || soap_put_SCOPE(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SCOPE(struct soap*, const enum SCOPE *, const char*, const char*);

#define soap_read_SCOPE(soap, data) ( soap_begin_recv(soap) || !soap_get_SCOPE(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum SCOPE * SOAP_FMAC4 soap_get_SCOPE(struct soap*, enum SCOPE *, const char*, const char*);

#ifndef SOAP_TYPE_FILE_TYPE
#define SOAP_TYPE_FILE_TYPE (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_FILE_TYPE(struct soap*, enum FILE_TYPE *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_FILE_TYPE(struct soap*, const char*, int, const enum FILE_TYPE *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_FILE_TYPE2s(struct soap*, enum FILE_TYPE);
SOAP_FMAC3 enum FILE_TYPE * SOAP_FMAC4 soap_in_FILE_TYPE(struct soap*, const char*, enum FILE_TYPE *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2FILE_TYPE(struct soap*, const char*, enum FILE_TYPE *);

#define soap_write_FILE_TYPE(soap, data) ( soap_begin_send(soap) || soap_put_FILE_TYPE(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_FILE_TYPE(struct soap*, const enum FILE_TYPE *, const char*, const char*);

#define soap_read_FILE_TYPE(soap, data) ( soap_begin_recv(soap) || !soap_get_FILE_TYPE(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum FILE_TYPE * SOAP_FMAC4 soap_get_FILE_TYPE(struct soap*, enum FILE_TYPE *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_txbr__statOFFTxbr
#define SOAP_TYPE_txbr__statOFFTxbr (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_txbr__statOFFTxbr(struct soap*, struct txbr__statOFFTxbr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_txbr__statOFFTxbr(struct soap*, const struct txbr__statOFFTxbr *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_txbr__statOFFTxbr(struct soap*, const char*, int, const struct txbr__statOFFTxbr *, const char*);
SOAP_FMAC3 struct txbr__statOFFTxbr * SOAP_FMAC4 soap_in_txbr__statOFFTxbr(struct soap*, const char*, struct txbr__statOFFTxbr *, const char*);

#define soap_write_txbr__statOFFTxbr(soap, data) ( soap_begin_send(soap) || (soap_serialize_txbr__statOFFTxbr(soap, data), 0) || soap_put_txbr__statOFFTxbr(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_txbr__statOFFTxbr(struct soap*, const struct txbr__statOFFTxbr *, const char*, const char*);

#define soap_read_txbr__statOFFTxbr(soap, data) ( soap_begin_recv(soap) || !soap_get_txbr__statOFFTxbr(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct txbr__statOFFTxbr * SOAP_FMAC4 soap_get_txbr__statOFFTxbr(struct soap*, struct txbr__statOFFTxbr *, const char*, const char*);

#define soap_new_txbr__statOFFTxbr(soap, n) soap_instantiate_txbr__statOFFTxbr(soap, n, NULL, NULL, NULL)


#define soap_delete_txbr__statOFFTxbr(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct txbr__statOFFTxbr * SOAP_FMAC2 soap_instantiate_txbr__statOFFTxbr(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_txbr__statOFFTxbr(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_txbr__statOFFTxbrResponse
#define SOAP_TYPE_txbr__statOFFTxbrResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_txbr__statOFFTxbrResponse(struct soap*, struct txbr__statOFFTxbrResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_txbr__statOFFTxbrResponse(struct soap*, const struct txbr__statOFFTxbrResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_txbr__statOFFTxbrResponse(struct soap*, const char*, int, const struct txbr__statOFFTxbrResponse *, const char*);
SOAP_FMAC3 struct txbr__statOFFTxbrResponse * SOAP_FMAC4 soap_in_txbr__statOFFTxbrResponse(struct soap*, const char*, struct txbr__statOFFTxbrResponse *, const char*);

#define soap_write_txbr__statOFFTxbrResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_txbr__statOFFTxbrResponse(soap, data), 0) || soap_put_txbr__statOFFTxbrResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_txbr__statOFFTxbrResponse(struct soap*, const struct txbr__statOFFTxbrResponse *, const char*, const char*);

#define soap_read_txbr__statOFFTxbrResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_txbr__statOFFTxbrResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct txbr__statOFFTxbrResponse * SOAP_FMAC4 soap_get_txbr__statOFFTxbrResponse(struct soap*, struct txbr__statOFFTxbrResponse *, const char*, const char*);

#define soap_new_txbr__statOFFTxbrResponse(soap, n) soap_instantiate_txbr__statOFFTxbrResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_txbr__statOFFTxbrResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct txbr__statOFFTxbrResponse * SOAP_FMAC2 soap_instantiate_txbr__statOFFTxbrResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_txbr__statOFFTxbrResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_txbr__resetOFFTxbr
#define SOAP_TYPE_txbr__resetOFFTxbr (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_txbr__resetOFFTxbr(struct soap*, struct txbr__resetOFFTxbr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_txbr__resetOFFTxbr(struct soap*, const struct txbr__resetOFFTxbr *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_txbr__resetOFFTxbr(struct soap*, const char*, int, const struct txbr__resetOFFTxbr *, const char*);
SOAP_FMAC3 struct txbr__resetOFFTxbr * SOAP_FMAC4 soap_in_txbr__resetOFFTxbr(struct soap*, const char*, struct txbr__resetOFFTxbr *, const char*);

#define soap_write_txbr__resetOFFTxbr(soap, data) ( soap_begin_send(soap) || (soap_serialize_txbr__resetOFFTxbr(soap, data), 0) || soap_put_txbr__resetOFFTxbr(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_txbr__resetOFFTxbr(struct soap*, const struct txbr__resetOFFTxbr *, const char*, const char*);

#define soap_read_txbr__resetOFFTxbr(soap, data) ( soap_begin_recv(soap) || !soap_get_txbr__resetOFFTxbr(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct txbr__resetOFFTxbr * SOAP_FMAC4 soap_get_txbr__resetOFFTxbr(struct soap*, struct txbr__resetOFFTxbr *, const char*, const char*);

#define soap_new_txbr__resetOFFTxbr(soap, n) soap_instantiate_txbr__resetOFFTxbr(soap, n, NULL, NULL, NULL)


#define soap_delete_txbr__resetOFFTxbr(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct txbr__resetOFFTxbr * SOAP_FMAC2 soap_instantiate_txbr__resetOFFTxbr(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_txbr__resetOFFTxbr(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_txbr__resetOFFTxbrResponse
#define SOAP_TYPE_txbr__resetOFFTxbrResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_txbr__resetOFFTxbrResponse(struct soap*, struct txbr__resetOFFTxbrResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_txbr__resetOFFTxbrResponse(struct soap*, const struct txbr__resetOFFTxbrResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_txbr__resetOFFTxbrResponse(struct soap*, const char*, int, const struct txbr__resetOFFTxbrResponse *, const char*);
SOAP_FMAC3 struct txbr__resetOFFTxbrResponse * SOAP_FMAC4 soap_in_txbr__resetOFFTxbrResponse(struct soap*, const char*, struct txbr__resetOFFTxbrResponse *, const char*);

#define soap_write_txbr__resetOFFTxbrResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_txbr__resetOFFTxbrResponse(soap, data), 0) || soap_put_txbr__resetOFFTxbrResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_txbr__resetOFFTxbrResponse(struct soap*, const struct txbr__resetOFFTxbrResponse *, const char*, const char*);

#define soap_read_txbr__resetOFFTxbrResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_txbr__resetOFFTxbrResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct txbr__resetOFFTxbrResponse * SOAP_FMAC4 soap_get_txbr__resetOFFTxbrResponse(struct soap*, struct txbr__resetOFFTxbrResponse *, const char*, const char*);

#define soap_new_txbr__resetOFFTxbrResponse(soap, n) soap_instantiate_txbr__resetOFFTxbrResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_txbr__resetOFFTxbrResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct txbr__resetOFFTxbrResponse * SOAP_FMAC2 soap_instantiate_txbr__resetOFFTxbrResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_txbr__resetOFFTxbrResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_txbr__runOFFTxbr
#define SOAP_TYPE_txbr__runOFFTxbr (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_txbr__runOFFTxbr(struct soap*, struct txbr__runOFFTxbr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_txbr__runOFFTxbr(struct soap*, const struct txbr__runOFFTxbr *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_txbr__runOFFTxbr(struct soap*, const char*, int, const struct txbr__runOFFTxbr *, const char*);
SOAP_FMAC3 struct txbr__runOFFTxbr * SOAP_FMAC4 soap_in_txbr__runOFFTxbr(struct soap*, const char*, struct txbr__runOFFTxbr *, const char*);

#define soap_write_txbr__runOFFTxbr(soap, data) ( soap_begin_send(soap) || (soap_serialize_txbr__runOFFTxbr(soap, data), 0) || soap_put_txbr__runOFFTxbr(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_txbr__runOFFTxbr(struct soap*, const struct txbr__runOFFTxbr *, const char*, const char*);

#define soap_read_txbr__runOFFTxbr(soap, data) ( soap_begin_recv(soap) || !soap_get_txbr__runOFFTxbr(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct txbr__runOFFTxbr * SOAP_FMAC4 soap_get_txbr__runOFFTxbr(struct soap*, struct txbr__runOFFTxbr *, const char*, const char*);

#define soap_new_txbr__runOFFTxbr(soap, n) soap_instantiate_txbr__runOFFTxbr(soap, n, NULL, NULL, NULL)


#define soap_delete_txbr__runOFFTxbr(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct txbr__runOFFTxbr * SOAP_FMAC2 soap_instantiate_txbr__runOFFTxbr(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_txbr__runOFFTxbr(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_txbr__runOFFTxbrResponse
#define SOAP_TYPE_txbr__runOFFTxbrResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_txbr__runOFFTxbrResponse(struct soap*, struct txbr__runOFFTxbrResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_txbr__runOFFTxbrResponse(struct soap*, const struct txbr__runOFFTxbrResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_txbr__runOFFTxbrResponse(struct soap*, const char*, int, const struct txbr__runOFFTxbrResponse *, const char*);
SOAP_FMAC3 struct txbr__runOFFTxbrResponse * SOAP_FMAC4 soap_in_txbr__runOFFTxbrResponse(struct soap*, const char*, struct txbr__runOFFTxbrResponse *, const char*);

#define soap_write_txbr__runOFFTxbrResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_txbr__runOFFTxbrResponse(soap, data), 0) || soap_put_txbr__runOFFTxbrResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_txbr__runOFFTxbrResponse(struct soap*, const struct txbr__runOFFTxbrResponse *, const char*, const char*);

#define soap_read_txbr__runOFFTxbrResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_txbr__runOFFTxbrResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct txbr__runOFFTxbrResponse * SOAP_FMAC4 soap_get_txbr__runOFFTxbrResponse(struct soap*, struct txbr__runOFFTxbrResponse *, const char*, const char*);

#define soap_new_txbr__runOFFTxbrResponse(soap, n) soap_instantiate_txbr__runOFFTxbrResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_txbr__runOFFTxbrResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct txbr__runOFFTxbrResponse * SOAP_FMAC2 soap_instantiate_txbr__runOFFTxbrResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_txbr__runOFFTxbrResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
