/* soapProxy.h
   Generated by gSOAP 2.7.17 from txbrHeader.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapServiceProxy_H
#define soapServiceProxy_H
#include "soapH.h"
class Service
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'Service' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	Service()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"txbr", "http://tempuri.org/txbr.xsd", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~Service() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'runOFFTxbr' of service 'Service' and return error code (or SOAP_OK)
	virtual int txbr__runOFFTxbr(char *fileFolderLocation, char *workDirectory, char *basename, enum FILE_TYPE type, enum SCOPE scope, int &return_val) { return soap ? soap_call_txbr__runOFFTxbr(soap, endpoint, NULL, fileFolderLocation, workDirectory, basename, type, scope, return_val) : SOAP_EOM; };
	/// Invoke 'resetOFFTxbr' of service 'Service' and return error code (or SOAP_OK)
	virtual int txbr__resetOFFTxbr(char *workDirectory, int &return_val) { return soap ? soap_call_txbr__resetOFFTxbr(soap, endpoint, NULL, workDirectory, return_val) : SOAP_EOM; };
	/// Invoke 'statOFFTxbr' of service 'Service' and return error code (or SOAP_OK)
	virtual int txbr__statOFFTxbr(char *workDirectory, int &return_val) { return soap ? soap_call_txbr__statOFFTxbr(soap, endpoint, NULL, workDirectory, return_val) : SOAP_EOM; };
};
#endif
