/* Generated by Pyrex 0.9.6.4 on Tue Apr  5 13:45:33 2011 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdlib.h"
#include "string.h"
#include "math.h"
#include "numpy/arrayobject.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from c_python */


/* Declarations from c_numpy */

static PyTypeObject *__pyx_ptype_7c_numpy_dtype = 0;
static PyTypeObject *__pyx_ptype_7c_numpy_ndarray = 0;
static PyTypeObject *__pyx_ptype_7c_numpy_flatiter = 0;
static PyTypeObject *__pyx_ptype_7c_numpy_broadcast = 0;

/* Declarations from remapSupp */

static PyObject *__pyx_f_9remapSupp_remap_section_aff(int,PyArrayObject *,double,double,double,double,double,double,PyArrayObject *,int,int); /*proto*/
static PyObject *__pyx_f_9remapSupp_remap_section_proj(int,PyArrayObject *,double,double,double,double,double,double,double,double,double,double,double,double,PyArrayObject *,int,int,int); /*proto*/
static PyObject *__pyx_f_9remapSupp_p(double,double,double,double,double); /*proto*/


/* Implementation of remapSupp */

static PyObject *__pyx_n_NO_INTERPOLATION;
static PyObject *__pyx_n_BILINEAR_INTERPOLATION;
static PyObject *__pyx_n_BICUBIC_INTERPOLATION;

static PyObject *__pyx_n_shape;

static PyObject *__pyx_f_9remapSupp_remap_aff(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9remapSupp_remap_aff(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_sections = 0;
  PyObject *__pyx_v_transformation = 0;
  PyObject *__pyx_v_final_section = 0;
  int __pyx_v_nx;
  int __pyx_v_ny;
  double __pyx_v_tx;
  double __pyx_v_axx;
  double __pyx_v_axy;
  double __pyx_v_ty;
  double __pyx_v_ayx;
  double __pyx_v_ayy;
  PyObject *__pyx_v_iquadrant;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  long __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  double __pyx_8;
  static char *__pyx_argnames[] = {"sections","transformation","final_section",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_sections, &__pyx_v_transformation, &__pyx_v_final_section)) return 0;
  Py_INCREF(__pyx_v_sections);
  Py_INCREF(__pyx_v_transformation);
  Py_INCREF(__pyx_v_final_section);
  __pyx_v_iquadrant = Py_None; Py_INCREF(Py_None);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":25 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_final_section, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_nx = __pyx_3;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_ny = __pyx_3;
  if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":27 */
  for (__pyx_4 = 0; __pyx_4 < 4; ++__pyx_4) {
    __pyx_1 = PyInt_FromLong(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
    Py_DECREF(__pyx_v_iquadrant);
    __pyx_v_iquadrant = __pyx_1;
    __pyx_1 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":29 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_1 = PyInt_FromLong(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_5 = PyNumber_Multiply(__pyx_1, __pyx_v_iquadrant); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyInt_FromLong(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_1, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyInt_FromLong(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_7 = PyNumber_Add(__pyx_6, __pyx_1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_6 = PySlice_New(__pyx_5, __pyx_7, Py_None); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_1, 1, __pyx_6);
    __pyx_2 = 0;
    __pyx_6 = 0;
    __pyx_5 = PyObject_GetItem(__pyx_v_transformation, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_7 = PyObject_GetIter(__pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_2 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_tx = __pyx_8;
    __pyx_6 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_v_axx = __pyx_8;
    __pyx_1 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_axy = __pyx_8;
    if (__Pyx_EndUnpack(__pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":30 */
    __pyx_5 = PyInt_FromLong(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_2, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyInt_FromLong(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_7 = PyNumber_Multiply(__pyx_1, __pyx_v_iquadrant); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyInt_FromLong(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_1 = PyNumber_Add(__pyx_7, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PySlice_New(__pyx_6, __pyx_1, Py_None); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_7);
    __pyx_5 = 0;
    __pyx_7 = 0;
    __pyx_6 = PyObject_GetItem(__pyx_v_transformation, __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyObject_GetIter(__pyx_6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_5 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_ty = __pyx_8;
    __pyx_7 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_7); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_v_ayx = __pyx_8;
    __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_ayy = __pyx_8;
    if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":32 */
    __pyx_3 = PyInt_AsLong(__pyx_v_iquadrant); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_6 = PyObject_GetItem(__pyx_v_sections, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    if (!__Pyx_TypeTest(__pyx_6, __pyx_ptype_7c_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    if (!__Pyx_TypeTest(__pyx_v_final_section, __pyx_ptype_7c_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_5 = __pyx_f_9remapSupp_remap_section_aff(__pyx_3,((PyArrayObject *)__pyx_6),__pyx_v_tx,__pyx_v_axx,__pyx_v_axy,__pyx_v_ty,__pyx_v_ayx,__pyx_v_ayy,((PyArrayObject *)__pyx_v_final_section),__pyx_v_nx,__pyx_v_ny); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("remapSupp.remap_aff");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_iquadrant);
  Py_DECREF(__pyx_v_sections);
  Py_DECREF(__pyx_v_transformation);
  Py_DECREF(__pyx_v_final_section);
  return __pyx_r;
}

static PyObject *__pyx_k1p;

static char __pyx_k1[] = "Quadrant #%i";

static PyObject *__pyx_f_9remapSupp_remap_proj(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9remapSupp_remap_proj(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_sections = 0;
  PyObject *__pyx_v_transformation = 0;
  PyObject *__pyx_v_final_section = 0;
  PyObject *__pyx_v_interp = 0;
  int __pyx_v_nx;
  int __pyx_v_ny;
  double __pyx_v_tx;
  double __pyx_v_a00;
  double __pyx_v_a01;
  double __pyx_v_a02;
  double __pyx_v_ty;
  double __pyx_v_a10;
  double __pyx_v_a11;
  double __pyx_v_a12;
  double __pyx_v_lam_0;
  double __pyx_v_lam_1;
  double __pyx_v_lam_01;
  PyObject *__pyx_v_iquadrant;
  PyObject *__pyx_v_lam;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  long __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  double __pyx_8;
  int __pyx_9;
  static char *__pyx_argnames[] = {"sections","transformation","final_section","interp",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_sections, &__pyx_v_transformation, &__pyx_v_final_section, &__pyx_v_interp)) return 0;
  Py_INCREF(__pyx_v_sections);
  Py_INCREF(__pyx_v_transformation);
  Py_INCREF(__pyx_v_final_section);
  Py_INCREF(__pyx_v_interp);
  __pyx_v_iquadrant = Py_None; Py_INCREF(Py_None);
  __pyx_v_lam = Py_None; Py_INCREF(Py_None);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":45 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_final_section, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_nx = __pyx_3;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_ny = __pyx_3;
  if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":47 */
  if (__Pyx_PrintItem(__pyx_v_transformation) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":49 */
  for (__pyx_4 = 0; __pyx_4 < 4; ++__pyx_4) {
    __pyx_1 = PyInt_FromLong(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_v_iquadrant);
    __pyx_v_iquadrant = __pyx_1;
    __pyx_1 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":51 */
    __pyx_2 = PyNumber_Remainder(__pyx_k1p, __pyx_v_iquadrant); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":52 */
    __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    __pyx_5 = PyNumber_Multiply(__pyx_2, __pyx_v_iquadrant); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_2, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    __pyx_7 = PyNumber_Add(__pyx_6, __pyx_2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_6 = PySlice_New(__pyx_5, __pyx_7, Py_None); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_6);
    __pyx_1 = 0;
    __pyx_6 = 0;
    __pyx_5 = PyObject_GetItem(__pyx_v_transformation, __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintItem(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":53 */
    __pyx_7 = PyInt_FromLong(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_1, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __pyx_5 = PyNumber_Multiply(__pyx_2, __pyx_v_iquadrant); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __pyx_2 = PyNumber_Add(__pyx_5, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_5 = PySlice_New(__pyx_6, __pyx_2, Py_None); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_7);
    PyTuple_SET_ITEM(__pyx_1, 1, __pyx_5);
    __pyx_7 = 0;
    __pyx_5 = 0;
    __pyx_6 = PyObject_GetItem(__pyx_v_transformation, __pyx_1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (__Pyx_PrintItem(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":54 */
    __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_7 = PyInt_FromLong(4); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_5 = PyNumber_Multiply(__pyx_7, __pyx_v_iquadrant); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_1, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_7 = PyInt_FromLong(4); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_1 = PyNumber_Add(__pyx_6, __pyx_7); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_6 = PySlice_New(__pyx_5, __pyx_1, Py_None); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_6);
    __pyx_2 = 0;
    __pyx_6 = 0;
    __pyx_5 = PyObject_GetItem(__pyx_v_transformation, __pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    if (__Pyx_PrintItem(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":56 */
    __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_2, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyInt_FromLong(4); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_5 = PyNumber_Multiply(__pyx_7, __pyx_v_iquadrant); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_7 = PyNumber_Add(__pyx_5, __pyx_2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PySlice_New(__pyx_6, __pyx_7, Py_None); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_5);
    __pyx_1 = 0;
    __pyx_5 = 0;
    __pyx_6 = PyObject_GetItem(__pyx_v_transformation, __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyObject_GetIter(__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_tx = __pyx_8;
    __pyx_5 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_a00 = __pyx_8;
    __pyx_2 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_a01 = __pyx_8;
    __pyx_6 = __Pyx_UnpackItem(__pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_v_a02 = __pyx_8;
    if (__Pyx_EndUnpack(__pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":57 */
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_5 = PyInt_FromLong(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_2 = PyNumber_Multiply(__pyx_5, __pyx_v_iquadrant); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_6 = PyInt_FromLong(4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_7 = PyNumber_Multiply(__pyx_6, __pyx_v_iquadrant); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_5 = PyInt_FromLong(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_6 = PyNumber_Add(__pyx_7, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_7 = PySlice_New(__pyx_2, __pyx_6, Py_None); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_7);
    __pyx_1 = 0;
    __pyx_7 = 0;
    __pyx_2 = PyObject_GetItem(__pyx_v_transformation, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_6 = PyObject_GetIter(__pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_ty = __pyx_8;
    __pyx_7 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_7); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_v_a10 = __pyx_8;
    __pyx_5 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_a11 = __pyx_8;
    __pyx_2 = __Pyx_UnpackItem(__pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_a12 = __pyx_8;
    if (__Pyx_EndUnpack(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":58 */
    __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_7 = PyInt_FromLong(4); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_5 = PyNumber_Multiply(__pyx_7, __pyx_v_iquadrant); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_6 = PyNumber_Multiply(__pyx_2, __pyx_v_iquadrant); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyInt_FromLong(4); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_2 = PyNumber_Add(__pyx_6, __pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_6 = PySlice_New(__pyx_5, __pyx_2, Py_None); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_6);
    __pyx_1 = 0;
    __pyx_6 = 0;
    __pyx_5 = PyObject_GetItem(__pyx_v_transformation, __pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_v_lam);
    __pyx_v_lam = __pyx_1;
    __pyx_1 = 0;
    __pyx_6 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_v_lam_0 = __pyx_8;
    __pyx_7 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_7); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_v_lam_1 = __pyx_8;
    __pyx_5 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_lam_01 = __pyx_8;
    if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":60 */
    __pyx_3 = PyInt_AsLong(__pyx_v_iquadrant); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_v_sections, __pyx_v_iquadrant); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_7c_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_v_lam); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    if (!__Pyx_TypeTest(__pyx_v_final_section, __pyx_ptype_7c_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_9 = PyInt_AsLong(__pyx_v_interp); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_6 = __pyx_f_9remapSupp_remap_section_proj(__pyx_3,((PyArrayObject *)__pyx_1),__pyx_v_tx,__pyx_v_a00,__pyx_v_a01,__pyx_v_a02,__pyx_v_ty,__pyx_v_a10,__pyx_v_a11,__pyx_v_a12,__pyx_8,__pyx_v_lam_0,__pyx_v_lam_1,__pyx_v_lam_01,((PyArrayObject *)__pyx_v_final_section),__pyx_v_nx,__pyx_v_ny,__pyx_9); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("remapSupp.remap_proj");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_iquadrant);
  Py_DECREF(__pyx_v_lam);
  Py_DECREF(__pyx_v_sections);
  Py_DECREF(__pyx_v_transformation);
  Py_DECREF(__pyx_v_final_section);
  Py_DECREF(__pyx_v_interp);
  return __pyx_r;
}

static PyObject *__pyx_f_9remapSupp_remap_section_aff(int __pyx_v_iquadrant,PyArrayObject *__pyx_v_section,double __pyx_v_tx,double __pyx_v_axx,double __pyx_v_axy,double __pyx_v_ty,double __pyx_v_ayx,double __pyx_v_ayy,PyArrayObject *__pyx_v_final_section,int __pyx_v_nx,int __pyx_v_ny) {
  int __pyx_v_dbl_block;
  int __pyx_v_width;
  int __pyx_v_i;
  double *__pyx_v_weight_x;
  double *__pyx_v_weight_y;
  int __pyx_v_x0;
  int __pyx_v_x1;
  int __pyx_v_y0;
  int __pyx_v_y1;
  int __pyx_v_nx_;
  int __pyx_v_ny_;
  int __pyx_v_ix;
  int __pyx_v_iy;
  int __pyx_v_xv;
  int __pyx_v_yv;
  double __pyx_v_value;
  double __pyx_v_x_proj;
  double __pyx_v_y_proj;
  double __pyx_v_x_diff;
  double __pyx_v_y_diff;
  double *__pyx_v_data;
  double *__pyx_v_data_q;
  int __pyx_v_index;
  int __pyx_v_index_q_00;
  int __pyx_v_index_q_01;
  int __pyx_v_index_q_10;
  int __pyx_v_index_q_11;
  int __pyx_v_strf_1;
  int __pyx_v_strf_2;
  int __pyx_v_strf_q_1;
  int __pyx_v_strf_q_2;
  PyObject *__pyx_r;
  int __pyx_1;
  long __pyx_2;
  Py_INCREF(__pyx_v_section);
  Py_INCREF(__pyx_v_final_section);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":69 */
  __pyx_v_dbl_block = 8;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":74 */
  __pyx_v_width = 1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":76 */
  __pyx_v_weight_x = ((double *)malloc((__pyx_v_dbl_block * __pyx_v_nx)));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":77 */
  __pyx_v_weight_y = ((double *)malloc((__pyx_v_dbl_block * __pyx_v_ny)));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":79 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_nx; ++__pyx_v_i) {
    (__pyx_v_weight_x[__pyx_v_i]) = 0.0;
  }

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":80 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_ny; ++__pyx_v_i) {
    (__pyx_v_weight_y[__pyx_v_i]) = 0.0;
  }

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":85 */
  __pyx_v_nx_ = (__pyx_v_nx / 2);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":86 */
  __pyx_v_ny_ = (__pyx_v_ny / 2);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":88 */
  __pyx_v_x0 = 1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":89 */
  __pyx_v_y0 = 1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":91 */
  __pyx_v_x1 = (__pyx_v_x0 + __pyx_v_nx_);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":92 */
  __pyx_v_y1 = (__pyx_v_y0 + __pyx_v_ny_);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":94 */
  __pyx_1 = (__pyx_v_iquadrant == 0);
  if (__pyx_1) {

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":96 */
    __pyx_v_x0 = 1;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":97 */
    __pyx_v_x1 = ((__pyx_v_x0 + __pyx_v_nx_) + __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":98 */
    __pyx_2 = (__pyx_v_x1 - (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_x0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = 1.0;
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":99 */
    for (__pyx_v_i = (__pyx_v_x1 - (2 * __pyx_v_width)); __pyx_v_i <= __pyx_v_x1; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = ((__pyx_v_x1 - __pyx_v_i) / (2.0 * __pyx_v_width));
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":101 */
    __pyx_v_y0 = ((__pyx_v_ny_ + 1) - __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":102 */
    __pyx_v_y1 = (__pyx_v_y0 + __pyx_v_ny_);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":103 */
    __pyx_2 = (__pyx_v_y0 + (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_y0; __pyx_v_i <= __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = ((__pyx_v_i - __pyx_v_y0) / (2.0 * __pyx_v_width));
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":104 */
    for (__pyx_v_i = (__pyx_v_y0 + (2 * __pyx_v_width))+1; __pyx_v_i < __pyx_v_y1; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = 1.0;
    }
    goto __pyx_L6;
  }
  __pyx_1 = (__pyx_v_iquadrant == 1);
  if (__pyx_1) {

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":108 */
    __pyx_v_x0 = ((__pyx_v_nx_ + 1) - __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":109 */
    __pyx_v_x1 = (__pyx_v_x0 + __pyx_v_nx_);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":110 */
    __pyx_2 = (__pyx_v_x0 + (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_x0; __pyx_v_i <= __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = ((__pyx_v_i - __pyx_v_x0) / (2.0 * __pyx_v_width));
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":111 */
    for (__pyx_v_i = (__pyx_v_x0 + (2 * __pyx_v_width))+1; __pyx_v_i < __pyx_v_x1; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = 1.0;
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":113 */
    __pyx_v_y0 = ((__pyx_v_ny_ + 1) - __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":114 */
    __pyx_v_y1 = (__pyx_v_y0 + __pyx_v_ny_);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":115 */
    __pyx_2 = (__pyx_v_y0 + (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_y0; __pyx_v_i <= __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = ((__pyx_v_i - __pyx_v_y0) / (2.0 * __pyx_v_width));
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":116 */
    for (__pyx_v_i = (__pyx_v_y0 + (2 * __pyx_v_width)); __pyx_v_i < __pyx_v_y1; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = 1.0;
    }
    goto __pyx_L6;
  }
  __pyx_1 = (__pyx_v_iquadrant == 2);
  if (__pyx_1) {

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":120 */
    __pyx_v_x0 = ((__pyx_v_nx_ + 1) - __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":121 */
    __pyx_v_x1 = (__pyx_v_x0 + __pyx_v_nx_);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":122 */
    __pyx_2 = (__pyx_v_x0 + (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_x0; __pyx_v_i <= __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = ((__pyx_v_i - __pyx_v_x0) / (2.0 * __pyx_v_width));
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":123 */
    for (__pyx_v_i = (__pyx_v_x0 + (2 * __pyx_v_width))+1; __pyx_v_i < __pyx_v_x1; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = 1.0;
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":125 */
    __pyx_v_y0 = 1;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":126 */
    __pyx_v_y1 = ((__pyx_v_y0 + __pyx_v_ny_) + __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":127 */
    __pyx_2 = (__pyx_v_y1 - (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_y0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = 1.0;
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":128 */
    for (__pyx_v_i = (__pyx_v_y1 - (2 * __pyx_v_width)); __pyx_v_i <= __pyx_v_y1; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = ((__pyx_v_y1 - __pyx_v_i) / (2.0 * __pyx_v_width));
    }
    goto __pyx_L6;
  }
  __pyx_1 = (__pyx_v_iquadrant == 3);
  if (__pyx_1) {

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":132 */
    __pyx_v_x0 = 1;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":133 */
    __pyx_v_x1 = ((__pyx_v_x0 + __pyx_v_nx_) + __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":134 */
    __pyx_2 = (__pyx_v_x1 - (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_x0; __pyx_v_i <= __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = 1.0;
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":135 */
    for (__pyx_v_i = (__pyx_v_x1 - (2 * __pyx_v_width))+1; __pyx_v_i <= __pyx_v_x1; ++__pyx_v_i) {
      (__pyx_v_weight_x[__pyx_v_i]) = ((__pyx_v_x1 - __pyx_v_i) / (2.0 * __pyx_v_width));
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":137 */
    __pyx_v_y0 = 1;

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":138 */
    __pyx_v_y1 = ((__pyx_v_y0 + __pyx_v_ny_) + __pyx_v_width);

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":139 */
    __pyx_2 = (__pyx_v_y1 - (2 * __pyx_v_width));
    for (__pyx_v_i = __pyx_v_y0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = 1.0;
    }

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":140 */
    for (__pyx_v_i = (__pyx_v_y1 - (2 * __pyx_v_width)); __pyx_v_i <= __pyx_v_y1; ++__pyx_v_i) {
      (__pyx_v_weight_y[__pyx_v_i]) = ((__pyx_v_y1 - __pyx_v_i) / (2.0 * __pyx_v_width));
    }
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":150 */
  __pyx_v_data = ((double *)PyArray_DATA(__pyx_v_final_section));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":151 */
  __pyx_v_data_q = ((double *)PyArray_DATA(__pyx_v_section));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":153 */
  __pyx_v_strf_1 = ((__pyx_v_final_section->strides[0]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":154 */
  __pyx_v_strf_2 = ((__pyx_v_final_section->strides[1]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":156 */
  __pyx_v_strf_q_1 = ((__pyx_v_section->strides[0]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":157 */
  __pyx_v_strf_q_2 = ((__pyx_v_section->strides[1]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":159 */
  for (__pyx_v_ix = __pyx_v_x0; __pyx_v_ix < __pyx_v_x1; ++__pyx_v_ix) {
    for (__pyx_v_iy = __pyx_v_y0; __pyx_v_iy < __pyx_v_y1; ++__pyx_v_iy) {

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":161 */
      __pyx_v_x_proj = ((__pyx_v_tx + (__pyx_v_axx * __pyx_v_ix)) + (__pyx_v_axy * __pyx_v_iy));

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":162 */
      __pyx_v_y_proj = ((__pyx_v_ty + (__pyx_v_ayx * __pyx_v_ix)) + (__pyx_v_ayy * __pyx_v_iy));

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":163 */
      __pyx_v_xv = ((int)__pyx_v_x_proj);

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":164 */
      __pyx_v_yv = ((int)__pyx_v_y_proj);

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":165 */
      __pyx_v_x_diff = (__pyx_v_x_proj - __pyx_v_xv);

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":166 */
      __pyx_v_y_diff = (__pyx_v_y_proj - __pyx_v_yv);

      /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":167 */
      __pyx_1 = (__pyx_v_xv > 0);
      if (__pyx_1) {
        __pyx_1 = (__pyx_v_xv < (__pyx_v_nx_ - 1));
        if (__pyx_1) {
          __pyx_1 = (__pyx_v_yv > 0);
          if (__pyx_1) {
            __pyx_1 = (__pyx_v_yv < (__pyx_v_ny_ - 1));
          }
        }
      }
      if (__pyx_1) {

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":168 */
        __pyx_v_index = (((__pyx_v_ix - 1) * __pyx_v_strf_1) + ((__pyx_v_iy - 1) * __pyx_v_strf_2));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":169 */
        __pyx_v_index_q_00 = ((__pyx_v_xv * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":170 */
        __pyx_v_index_q_01 = ((__pyx_v_xv * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":171 */
        __pyx_v_index_q_10 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":172 */
        __pyx_v_index_q_11 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":174 */
        __pyx_v_value = (((((__pyx_v_x_diff * __pyx_v_y_diff) * (__pyx_v_data_q[__pyx_v_index_q_00])) + (((1.0 - __pyx_v_x_diff) * __pyx_v_y_diff) * (__pyx_v_data_q[__pyx_v_index_q_10]))) + ((__pyx_v_x_diff * (1.0 - __pyx_v_y_diff)) * (__pyx_v_data_q[__pyx_v_index_q_01]))) + (((1.0 - __pyx_v_x_diff) * (1.0 - __pyx_v_y_diff)) * (__pyx_v_data_q[__pyx_v_index_q_11])));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":175 */
        (__pyx_v_data[__pyx_v_index]) = ((__pyx_v_data[__pyx_v_index]) + ((__pyx_v_value * (__pyx_v_weight_x[__pyx_v_ix])) * (__pyx_v_weight_y[__pyx_v_iy])));
        goto __pyx_L43;
      }
      __pyx_L43:;
    }
  }

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":177 */
  free(__pyx_v_weight_x);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":178 */
  free(__pyx_v_weight_y);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_section);
  Py_DECREF(__pyx_v_final_section);
  return __pyx_r;
}

static PyObject *__pyx_n_max;
static PyObject *__pyx_n_min;

static PyObject *__pyx_k2p;

static char __pyx_k2[] = "x1=%i	y1=%i";

static PyObject *__pyx_f_9remapSupp_remap_section_proj(int __pyx_v_iquadrant,PyArrayObject *__pyx_v_section,double __pyx_v_tx,double __pyx_v_a00,double __pyx_v_a01,double __pyx_v_a02,double __pyx_v_ty,double __pyx_v_a10,double __pyx_v_a11,double __pyx_v_a12,double __pyx_v_lam,double __pyx_v_lam_0,double __pyx_v_lam_1,double __pyx_v_lam_01,PyArrayObject *__pyx_v_final_section,int __pyx_v_nx,int __pyx_v_ny,int __pyx_v_interp) {
  int __pyx_v_dbl_block;
  int __pyx_v_x0;
  int __pyx_v_x1;
  int __pyx_v_y0;
  int __pyx_v_y1;
  int __pyx_v_nx_;
  int __pyx_v_ny_;
  int __pyx_v_ix;
  int __pyx_v_iy;
  int __pyx_v_xv;
  int __pyx_v_yv;
  double __pyx_v_value;
  double __pyx_v_x_proj;
  double __pyx_v_y_proj;
  double __pyx_v_x_diff;
  double __pyx_v_y_diff;
  double __pyx_v_lambda_;
  double *__pyx_v_data;
  double *__pyx_v_data_q;
  int __pyx_v_index;
  int __pyx_v_index_q_00;
  int __pyx_v_index_q_01;
  int __pyx_v_index_q_10;
  int __pyx_v_index_q_11;
  int __pyx_v_strf_1;
  int __pyx_v_strf_2;
  int __pyx_v_strf_q_1;
  int __pyx_v_strf_q_2;
  double __pyx_v_secure_rate;
  int __pyx_v_index_q_m1;
  int __pyx_v_index_q_0;
  int __pyx_v_index_q_1;
  int __pyx_v_index_q_2;
  double __pyx_v_value_m1;
  double __pyx_v_value_0;
  double __pyx_v_value_1;
  double __pyx_v_value_2;
  PyObject *__pyx_r;
  int __pyx_1;
  long __pyx_2;
  long __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  double __pyx_8;
  Py_INCREF(__pyx_v_section);
  Py_INCREF(__pyx_v_final_section);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":188 */
  __pyx_v_dbl_block = 8;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":193 */
  __pyx_v_nx_ = (__pyx_v_nx / 2);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":194 */
  __pyx_v_ny_ = (__pyx_v_ny / 2);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":196 */
  __pyx_v_x0 = 1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":197 */
  __pyx_v_y0 = 1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":199 */
  __pyx_1 = (__pyx_v_iquadrant == 0);
  if (__pyx_1) {
    __pyx_2 = 1;
    __pyx_3 = (__pyx_v_ny_ + 1);
    __pyx_v_x0 = __pyx_2;
    __pyx_v_y0 = __pyx_3;
    goto __pyx_L2;
  }
  __pyx_1 = (__pyx_v_iquadrant == 1);
  if (__pyx_1) {
    __pyx_2 = (__pyx_v_nx_ + 1);
    __pyx_3 = (__pyx_v_ny_ + 1);
    __pyx_v_x0 = __pyx_2;
    __pyx_v_y0 = __pyx_3;
    goto __pyx_L2;
  }
  __pyx_1 = (__pyx_v_iquadrant == 2);
  if (__pyx_1) {
    __pyx_2 = (__pyx_v_nx_ + 1);
    __pyx_3 = 1;
    __pyx_v_x0 = __pyx_2;
    __pyx_v_y0 = __pyx_3;
    goto __pyx_L2;
  }
  __pyx_1 = (__pyx_v_iquadrant == 3);
  if (__pyx_1) {
    __pyx_2 = 1;
    __pyx_3 = 1;
    __pyx_v_x0 = __pyx_2;
    __pyx_v_y0 = __pyx_3;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":204 */
  __pyx_v_x1 = (__pyx_v_x0 + __pyx_v_nx_);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":205 */
  __pyx_v_y1 = (__pyx_v_y0 + __pyx_v_ny_);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":216 */
  __pyx_v_data = ((double *)PyArray_DATA(__pyx_v_final_section));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":217 */
  __pyx_v_data_q = ((double *)PyArray_DATA(__pyx_v_section));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":219 */
  __pyx_v_strf_1 = ((__pyx_v_final_section->strides[0]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":220 */
  __pyx_v_strf_2 = ((__pyx_v_final_section->strides[1]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":222 */
  __pyx_v_strf_q_1 = ((__pyx_v_section->strides[0]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":223 */
  __pyx_v_strf_q_2 = ((__pyx_v_section->strides[1]) / __pyx_v_dbl_block);

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":227 */
  __pyx_v_secure_rate = 0.1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":229 */
  __pyx_v_x0 = ((int)((1 - __pyx_v_secure_rate) * __pyx_v_x0));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":230 */
  __pyx_v_y0 = ((int)((1 - __pyx_v_secure_rate) * __pyx_v_y0));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":231 */
  __pyx_v_x1 = ((int)((1 + __pyx_v_secure_rate) * __pyx_v_x1));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":232 */
  __pyx_v_y1 = ((int)((1 + __pyx_v_secure_rate) * __pyx_v_y1));

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":234 */
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_max); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_6 = PyInt_FromLong(__pyx_v_x0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_5);
  PyTuple_SET_ITEM(__pyx_7, 1, __pyx_6);
  __pyx_5 = 0;
  __pyx_6 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_v_x0 = __pyx_1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":235 */
  __pyx_6 = __Pyx_GetName(__pyx_b, __pyx_n_max); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  __pyx_7 = PyInt_FromLong(__pyx_v_y0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_7);
  __pyx_4 = 0;
  __pyx_7 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_6, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_y0 = __pyx_1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":236 */
  __pyx_7 = __Pyx_GetName(__pyx_b, __pyx_n_min); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
  __pyx_6 = PyInt_FromLong((__pyx_v_nx + 1)); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_x1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_6);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_6 = 0;
  __pyx_5 = 0;
  __pyx_6 = PyObject_CallObject(__pyx_7, __pyx_4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_v_x1 = __pyx_1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":237 */
  __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_min); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  __pyx_7 = PyInt_FromLong((__pyx_v_ny + 1)); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_y1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_7);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
  __pyx_7 = 0;
  __pyx_4 = 0;
  __pyx_7 = PyObject_CallObject(__pyx_5, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_7); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  __pyx_v_y1 = __pyx_1;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":242 */
  __pyx_4 = PyInt_FromLong(__pyx_v_interp); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_NO_INTERPOLATION); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_4, __pyx_5, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_1) {

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":244 */
    __pyx_6 = PyInt_FromLong(__pyx_v_x1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    __pyx_7 = PyInt_FromLong(__pyx_v_y1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_6);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_7);
    __pyx_6 = 0;
    __pyx_7 = 0;
    __pyx_5 = PyNumber_Remainder(__pyx_k2p, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__Pyx_PrintItem(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}

    /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":246 */
    for (__pyx_v_ix = __pyx_v_x0; __pyx_v_ix < __pyx_v_x1; ++__pyx_v_ix) {
      for (__pyx_v_iy = __pyx_v_y0; __pyx_v_iy < __pyx_v_y1; ++__pyx_v_iy) {

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":250 */
        __pyx_v_x_proj = (((__pyx_v_tx + (__pyx_v_a00 * __pyx_v_ix)) + (__pyx_v_a01 * __pyx_v_iy)) + ((__pyx_v_a02 * __pyx_v_ix) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":251 */
        __pyx_v_y_proj = (((__pyx_v_ty + (__pyx_v_a10 * __pyx_v_ix)) + (__pyx_v_a11 * __pyx_v_iy)) + ((__pyx_v_a12 * __pyx_v_ix) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":252 */
        __pyx_v_lambda_ = (((__pyx_v_lam + (__pyx_v_lam_0 * __pyx_v_ix)) + (__pyx_v_lam_1 * __pyx_v_iy)) + ((__pyx_v_lam_01 * __pyx_v_ix) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":253 */
        __pyx_v_x_proj = ((__pyx_v_x_proj / __pyx_v_lambda_) - 1);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":254 */
        __pyx_v_y_proj = ((__pyx_v_y_proj / __pyx_v_lambda_) - 1);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":255 */
        __pyx_v_xv = ((int)__pyx_v_x_proj);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":256 */
        __pyx_v_yv = ((int)__pyx_v_y_proj);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":257 */
        __pyx_1 = (__pyx_v_xv > 0);
        if (__pyx_1) {
          __pyx_1 = (__pyx_v_xv < (__pyx_v_nx_ - 1));
          if (__pyx_1) {
            __pyx_1 = (__pyx_v_yv > 0);
            if (__pyx_1) {
              __pyx_1 = (__pyx_v_yv < (__pyx_v_ny_ - 1));
            }
          }
        }
        if (__pyx_1) {

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":258 */
          __pyx_v_index = (((__pyx_v_ix - 1) * __pyx_v_strf_1) + ((__pyx_v_iy - 1) * __pyx_v_strf_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":259 */
          __pyx_v_index_q_0 = ((__pyx_v_xv * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":260 */
          (__pyx_v_data[__pyx_v_index]) = (__pyx_v_data_q[__pyx_v_index_q_0]);
          goto __pyx_L8;
        }
        __pyx_L8:;
      }
    }
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":263 */
  __pyx_6 = PyInt_FromLong(__pyx_v_interp); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
  __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_BILINEAR_INTERPOLATION); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_6, __pyx_7, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  if (__pyx_1) {
    for (__pyx_v_ix = __pyx_v_x0; __pyx_v_ix < __pyx_v_x1; ++__pyx_v_ix) {
      for (__pyx_v_iy = __pyx_v_y0; __pyx_v_iy < __pyx_v_y1; ++__pyx_v_iy) {

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":269 */
        __pyx_v_x_proj = ((__pyx_v_tx + (__pyx_v_a00 * __pyx_v_ix)) + ((__pyx_v_a01 + (__pyx_v_a02 * __pyx_v_ix)) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":270 */
        __pyx_v_y_proj = ((__pyx_v_ty + (__pyx_v_a10 * __pyx_v_ix)) + ((__pyx_v_a11 + (__pyx_v_a12 * __pyx_v_ix)) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":271 */
        __pyx_v_lambda_ = ((__pyx_v_lam + (__pyx_v_lam_0 * __pyx_v_ix)) + ((__pyx_v_lam_1 + (__pyx_v_lam_01 * __pyx_v_ix)) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":272 */
        __pyx_v_x_proj = ((__pyx_v_x_proj / __pyx_v_lambda_) - 1);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":273 */
        __pyx_v_y_proj = ((__pyx_v_y_proj / __pyx_v_lambda_) - 1);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":274 */
        __pyx_v_xv = ((int)__pyx_v_x_proj);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":275 */
        __pyx_v_yv = ((int)__pyx_v_y_proj);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":276 */
        __pyx_v_x_diff = (__pyx_v_x_proj - __pyx_v_xv);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":277 */
        __pyx_v_y_diff = (__pyx_v_y_proj - __pyx_v_yv);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":278 */
        __pyx_1 = (__pyx_v_xv > 0);
        if (__pyx_1) {
          __pyx_1 = (__pyx_v_xv < (__pyx_v_nx_ - 2));
          if (__pyx_1) {
            __pyx_1 = (__pyx_v_yv > 0);
            if (__pyx_1) {
              __pyx_1 = (__pyx_v_yv < (__pyx_v_ny_ - 2));
            }
          }
        }
        if (__pyx_1) {

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":279 */
          __pyx_v_index = (((__pyx_v_ix - 1) * __pyx_v_strf_1) + ((__pyx_v_iy - 1) * __pyx_v_strf_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":280 */
          __pyx_v_index_q_00 = ((__pyx_v_xv * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":281 */
          __pyx_v_index_q_01 = ((__pyx_v_xv * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":282 */
          __pyx_v_index_q_10 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":283 */
          __pyx_v_index_q_11 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":285 */
          __pyx_v_value = (((((__pyx_v_x_diff * __pyx_v_y_diff) * (__pyx_v_data_q[__pyx_v_index_q_00])) + ((__pyx_v_x_diff * (1.0 - __pyx_v_y_diff)) * (__pyx_v_data_q[__pyx_v_index_q_01]))) + (((1.0 - __pyx_v_x_diff) * __pyx_v_y_diff) * (__pyx_v_data_q[__pyx_v_index_q_10]))) + (((1.0 - __pyx_v_x_diff) * (1.0 - __pyx_v_y_diff)) * (__pyx_v_data_q[__pyx_v_index_q_11])));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":286 */
          (__pyx_v_data[__pyx_v_index]) = __pyx_v_value;
          goto __pyx_L14;
        }
        __pyx_L14:;
      }
    }
    goto __pyx_L9;
  }
  __pyx_L9:;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":289 */
  __pyx_4 = PyInt_FromLong(__pyx_v_interp); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_BICUBIC_INTERPOLATION); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_4, __pyx_5, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_1) {
    for (__pyx_v_ix = __pyx_v_x0; __pyx_v_ix < __pyx_v_x1; ++__pyx_v_ix) {
      for (__pyx_v_iy = __pyx_v_y0; __pyx_v_iy < __pyx_v_y1; ++__pyx_v_iy) {

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":295 */
        __pyx_v_x_proj = ((__pyx_v_tx + (__pyx_v_a00 * __pyx_v_ix)) + ((__pyx_v_a01 + (__pyx_v_a02 * __pyx_v_ix)) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":296 */
        __pyx_v_y_proj = ((__pyx_v_ty + (__pyx_v_a10 * __pyx_v_ix)) + ((__pyx_v_a11 + (__pyx_v_a12 * __pyx_v_ix)) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":297 */
        __pyx_v_lambda_ = ((__pyx_v_lam + (__pyx_v_lam_0 * __pyx_v_ix)) + ((__pyx_v_lam_1 + (__pyx_v_lam_01 * __pyx_v_ix)) * __pyx_v_iy));

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":298 */
        __pyx_v_x_proj = ((__pyx_v_x_proj / __pyx_v_lambda_) - 1);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":299 */
        __pyx_v_y_proj = ((__pyx_v_y_proj / __pyx_v_lambda_) - 1);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":300 */
        __pyx_v_xv = ((int)__pyx_v_x_proj);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":301 */
        __pyx_v_yv = ((int)__pyx_v_y_proj);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":302 */
        __pyx_v_x_diff = (__pyx_v_x_proj - __pyx_v_xv);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":303 */
        __pyx_v_y_diff = (__pyx_v_y_proj - __pyx_v_yv);

        /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":305 */
        __pyx_1 = (__pyx_v_xv > 1);
        if (__pyx_1) {
          __pyx_1 = (__pyx_v_xv < (__pyx_v_nx_ - 3));
          if (__pyx_1) {
            __pyx_1 = (__pyx_v_yv > 1);
            if (__pyx_1) {
              __pyx_1 = (__pyx_v_yv < (__pyx_v_ny_ - 3));
            }
          }
        }
        if (__pyx_1) {

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":307 */
          __pyx_v_index = (((__pyx_v_ix - 1) * __pyx_v_strf_1) + ((__pyx_v_iy - 1) * __pyx_v_strf_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":309 */
          __pyx_v_index_q_m1 = (((__pyx_v_xv - 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv - 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":310 */
          __pyx_v_index_q_0 = ((__pyx_v_xv * __pyx_v_strf_q_1) + ((__pyx_v_yv - 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":311 */
          __pyx_v_index_q_1 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv - 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":312 */
          __pyx_v_index_q_2 = (((__pyx_v_xv + 2) * __pyx_v_strf_q_1) + ((__pyx_v_yv - 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":313 */
          __pyx_6 = __pyx_f_9remapSupp_p(__pyx_v_x_diff,(__pyx_v_data_q[__pyx_v_index_q_m1]),(__pyx_v_data_q[__pyx_v_index_q_0]),(__pyx_v_data_q[__pyx_v_index_q_1]),(__pyx_v_data_q[__pyx_v_index_q_2])); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 313; goto __pyx_L1;}
          __pyx_8 = PyFloat_AsDouble(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 313; goto __pyx_L1;}
          Py_DECREF(__pyx_6); __pyx_6 = 0;
          __pyx_v_value_m1 = __pyx_8;

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":315 */
          __pyx_v_index_q_m1 = (((__pyx_v_xv - 1) * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":316 */
          __pyx_v_index_q_0 = ((__pyx_v_xv * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":317 */
          __pyx_v_index_q_1 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":318 */
          __pyx_v_index_q_2 = (((__pyx_v_xv + 2) * __pyx_v_strf_q_1) + (__pyx_v_yv * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":319 */
          __pyx_7 = __pyx_f_9remapSupp_p(__pyx_v_x_diff,(__pyx_v_data_q[__pyx_v_index_q_m1]),(__pyx_v_data_q[__pyx_v_index_q_0]),(__pyx_v_data_q[__pyx_v_index_q_1]),(__pyx_v_data_q[__pyx_v_index_q_2])); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
          __pyx_8 = PyFloat_AsDouble(__pyx_7); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
          Py_DECREF(__pyx_7); __pyx_7 = 0;
          __pyx_v_value_0 = __pyx_8;

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":321 */
          __pyx_v_index_q_m1 = (((__pyx_v_xv - 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":322 */
          __pyx_v_index_q_0 = ((__pyx_v_xv * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":323 */
          __pyx_v_index_q_1 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":324 */
          __pyx_v_index_q_2 = (((__pyx_v_xv + 2) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 1) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":325 */
          __pyx_4 = __pyx_f_9remapSupp_p(__pyx_v_x_diff,(__pyx_v_data_q[__pyx_v_index_q_m1]),(__pyx_v_data_q[__pyx_v_index_q_0]),(__pyx_v_data_q[__pyx_v_index_q_1]),(__pyx_v_data_q[__pyx_v_index_q_2])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 325; goto __pyx_L1;}
          __pyx_8 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 325; goto __pyx_L1;}
          Py_DECREF(__pyx_4); __pyx_4 = 0;
          __pyx_v_value_1 = __pyx_8;

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":327 */
          __pyx_v_index_q_m1 = (((__pyx_v_xv - 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 2) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":328 */
          __pyx_v_index_q_0 = ((__pyx_v_xv * __pyx_v_strf_q_1) + ((__pyx_v_yv + 2) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":329 */
          __pyx_v_index_q_1 = (((__pyx_v_xv + 1) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 2) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":330 */
          __pyx_v_index_q_2 = (((__pyx_v_xv + 2) * __pyx_v_strf_q_1) + ((__pyx_v_yv + 2) * __pyx_v_strf_q_2));

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":331 */
          __pyx_5 = __pyx_f_9remapSupp_p(__pyx_v_x_diff,(__pyx_v_data_q[__pyx_v_index_q_m1]),(__pyx_v_data_q[__pyx_v_index_q_0]),(__pyx_v_data_q[__pyx_v_index_q_1]),(__pyx_v_data_q[__pyx_v_index_q_2])); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 331; goto __pyx_L1;}
          __pyx_8 = PyFloat_AsDouble(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 331; goto __pyx_L1;}
          Py_DECREF(__pyx_5); __pyx_5 = 0;
          __pyx_v_value_2 = __pyx_8;

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":333 */
          __pyx_6 = __pyx_f_9remapSupp_p(__pyx_v_y_diff,__pyx_v_value_m1,__pyx_v_value_0,__pyx_v_value_1,__pyx_v_value_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 333; goto __pyx_L1;}
          __pyx_8 = PyFloat_AsDouble(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 333; goto __pyx_L1;}
          Py_DECREF(__pyx_6); __pyx_6 = 0;
          __pyx_v_value = __pyx_8;

          /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":334 */
          (__pyx_v_data[__pyx_v_index]) = __pyx_v_value;
          goto __pyx_L20;
        }
        __pyx_L20:;
      }
    }
    goto __pyx_L15;
  }
  __pyx_L15:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("remapSupp.remap_section_proj");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_section);
  Py_DECREF(__pyx_v_final_section);
  return __pyx_r;
}

static PyObject *__pyx_f_9remapSupp_p(double __pyx_v_t,double __pyx_v_a_m1,double __pyx_v_a_0,double __pyx_v_a_1,double __pyx_v_a_2) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_1 = PyFloat_FromDouble((__pyx_v_a_0 + ((__pyx_v_t * ((__pyx_v_a_1 - __pyx_v_a_m1) + (__pyx_v_t * (((((2.0 * __pyx_v_a_m1) - (5.0 * __pyx_v_a_0)) + (4.0 * __pyx_v_a_1)) - __pyx_v_a_2) + (__pyx_v_t * ((((-__pyx_v_a_m1) + (3.0 * __pyx_v_a_0)) - (3.0 * __pyx_v_a_1)) + __pyx_v_a_2)))))) / 2.0))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 341; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("remapSupp.p");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_BICUBIC_INTERPOLATION, "BICUBIC_INTERPOLATION"},
  {&__pyx_n_BILINEAR_INTERPOLATION, "BILINEAR_INTERPOLATION"},
  {&__pyx_n_NO_INTERPOLATION, "NO_INTERPOLATION"},
  {&__pyx_n_max, "max"},
  {&__pyx_n_min, "min"},
  {&__pyx_n_shape, "shape"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"remap_aff", (PyCFunction)__pyx_f_9remapSupp_remap_aff, METH_VARARGS|METH_KEYWORDS, 0},
  {"remap_proj", (PyCFunction)__pyx_f_9remapSupp_remap_proj, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initremapSupp(void); /*proto*/
PyMODINIT_FUNC initremapSupp(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("remapSupp", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_ptype_7c_numpy_dtype = __Pyx_ImportType("numpy", "dtype", sizeof(PyArray_Descr)); if (!__pyx_ptype_7c_numpy_dtype) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_ptype_7c_numpy_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (!__pyx_ptype_7c_numpy_ndarray) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_ptype_7c_numpy_flatiter = __Pyx_ImportType("numpy", "flatiter", sizeof(PyArrayIterObject)); if (!__pyx_ptype_7c_numpy_flatiter) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_ptype_7c_numpy_broadcast = __Pyx_ImportType("numpy", "broadcast", sizeof(PyArrayMultiIterObject)); if (!__pyx_ptype_7c_numpy_broadcast) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 97; goto __pyx_L1;}

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":9 */
  import_array();

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":13 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_NO_INTERPOLATION, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":14 */
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_BILINEAR_INTERPOLATION, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":15 */
  __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_BICUBIC_INTERPOLATION, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/sphan/work/TxBR/TxBR/txbr/misc/remap/remapSupp.pyx":338 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("remapSupp");
}

static char *__pyx_filenames[] = {
  "remapSupp.pyx",
  "c_numpy.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    return PyImport_Import(py_name);
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
